{
    'name': 'PIE Grid',
    'category': 'Sales',
    'summary': 'PIE Grid Module',
    'version': '10.0.1.2.0',
    'website': 'https://www.businessborderlines.com',
    "author": "Kingfisher Consultancy , BusinessBorderlines",
    "sequence":15,
    'depends': ['PIE_Setup','mail'],
    'data': ['views/grid_view.xml','views/grid_actions.xml','views/grid_Menus.xml','security/ir.model.access.csv','security/user_groups.xml'],
    'image': [],
    'demo': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
}
